## XXXXコンテナのベースイメージを指定
# FROM XXXXX

## コンテナのOSのアップデート（必須）
run xxx xxxx

## アプリの実行に必要なpython3 と pipコマンドをインスール
#run apt install -y XXXXX

## pipコマンドでflaskをインストール
#run pip3 XXXXX 

## このファイルと同階層にあるapiディレクトリをimageに追加
# XXXX 

## コンテナ起動時のパスを指定
cmd ["xxxx","xxxxxx"]

